advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls')),
]
    

basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
	path('', views.SchoolListView.as_view(), name='list'),
	path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
	path('create/', views.SchoolCreateView.as_view(), name='create'),
	path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
	name = models.CharField(max_length=256)
	principal = models.CharField(max_length=200)
	location = models.CharField(max_length=256)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('basic_app:detail', kwargs={'pk':self.pk})

class Student(models.Model):
	name = models.CharField(max_length=256)
	age = models.PositiveIntegerField()
	school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

	def __str__(self):
		return self.name

basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from basic_app.models import School, Student
from django.urls import reverse_lazy

# Create your views here.
class IndexView(TemplateView):
	template_name = 'index.html'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['injectme'] = "Rushi is the best teacher"
		return context


class SchoolListView(ListView):
	model = School
	#returns school_list
	context_object_name = 'schools'

class SchoolDetailView(DetailView):
	model = School
	context_object_name = 'school_details'
	template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
	fields = ('name','principal','location')
	model = School

class SchoolUpdateView(UpdateView):
	fields = ('name', 'principal')
	model  = School

class SchoolDeleteView(DeleteView):
	model = School
	success_url = reverse_lazy("basic_app:list")
	context_object_name = 'school'

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
	<title></title>
</head>
<body>
	<nav class="navbar navbar-default">
		<ul class="navbar-nav">
			<li class="nav-item"> <a class="navbar-brand" href="{% url 'basic_app:list' %}"> Schools </a> </li>
			<li class="nav-item"> <a class="nav-link" href=" {% url 'admin:index' %} "> Admin </a> </li>
			<li class="nav-item"> <a class="nav-link" href=""></a> </li>
		</ul>
	</nav>

	{% block body_block %}
	{% endblock %}
</body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
	<h1>Delete {{school.name}}?</h1>
	<form method="post">
		{% csrf_token %}
		<input type="submit" class="btn btn-danger" value="Delete">
		<a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
	</form>
{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
	<div class="jumbotron">
		<h1>Welcome To The School Detail Page</h1>
		<h2>School Details:</h2>
		<p>Name: {{school_details.name}}</p>
		<p>Principal: {{school_details.principal}}</p>
		<p>Location: {{school_details.location}}</p>

		<h3>Students: </h3>
		{% for student in school_details.students.all %}
		 <p> {{student.name}} who is {{student.age}} years old </p>
		{% endfor %}
	</div>

	<div class="container" style="display: flex;">
		 <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_details.pk %}"> Update </a></p>
		 <p style="margin-left: 10px;"><a class="btn btn-warning" href="{% url 'basic_app:delete' pk=school_details.pk %}"> Delete	 </a></p>
	</div>

{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
	<div class="jumbotron">
		<h1>
			{% if not form.instance.pk %}
				Create School
			{% else %}
				Update School
			{% endif %}
		</h1>

		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" class="btn btn-primary" value="Submit">		
		</form>
	
	</div>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
	<h1>Welcome to list of all schools </h1>
	<ol>
		{% for school in schools %}
			<h2><li> <a href="{{school.id}}"> {{school.name}} </a> </li></h2>
		{% endfor %}
	</ol>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
	<title>Index</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg bg-body-tertiary">
		<ul class="navbar-nav">
			<li class="nav-item"> <a class="navbar-brand" href="{% url 'basic_app:list' %}"> Schools </a> </li>
			<li class="nav-item"> <a class="nav-link" href=" {% url 'admin:index' %} "> Admin </a> </li>
			<li class="nav-item"> <a class="nav-link" href="">Demo</a> </li>
		</ul>
	</nav>

	{% block body_block %}
		<div class="jumbotron">
			
		</div>
	{% endblock %}
</body>
</html>

templates/demo.html
{% extends 'base.html' %}

{% block body_block %}
	<h1>
		Demo Page for Git Practice
	</h1>
{% endblock %}
>>>>>>> new_templates

templates/index.html
{% extends 'base.html' %}

{% block body_block %}
	<div class="jumbotron">
		<h1>Home Page</h1>
	</div>
{% endblock %}